inherit_from: .rubocop_todo.yml

AllCops:
  # Keep this inline with the lowest ruby-* version in circleci/config.yml and
  # the version in the gemspec
  TargetRubyVersion: 2.2
  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the `-D/--display-cop-names`
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding `DisplayStyleGuide`, or by giving the
  # `-S/--display-style-guide` option.
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'lib/cucumber/formatter/legacy_api/*'
    - 'spec/cucumber/formatter/legacy_api/*'

# Reviewed: please see PR-1022 for details on why this cop is disabled:
# https://github.com/cucumber/cucumber-ruby/pull/1022
Lint/AmbiguousOperator:
  Enabled: false

# Disabling for appveyor
Layout/EndOfLine:
  Enabled: false

# Disabling this cop until the minimum Ruby version is >= 2.3 as squiggly
# heredocs '<<~' were introduced them. The files below are the current ones
# with offenses
Layout/IndentHeredoc:
  Exclude:
    - 'features/lib/support/feature_factory.rb'
    - 'lib/cucumber/cli/options.rb'
    - 'lib/cucumber/cli/profile_loader.rb'
    - 'spec/cucumber/cli/configuration_spec.rb'
    - 'spec/cucumber/cli/profile_loader_spec.rb'
    - 'spec/cucumber/formatter/pretty_spec.rb'

# Reviewed: Formatters put trailing spaces after things like 'Feature: '
#           In pretty_spec.rb, progress_spec.rb offences look false,
#           as the trailing spaces are in multiline string literals
Layout/TrailingWhitespace:
  Exclude:
    - 'spec/cucumber/formatter/pretty_spec.rb'
    - 'spec/cucumber/formatter/progress_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/cucumber/cli/options.rb'

# Rubocop doesn't like method names in other languages but as Cucumber supports 
# languages, this cop needs to be disabled.
Naming/AsciiIdentifiers:
  Enabled: false

# Reviewed: these offenses look false as the variables are in cyrillic
Naming/VariableName:
  Exclude:
    - 'examples/i18n/ru/features/step_definitions/calculator_steps.rb'
    - 'examples/i18n/uk/features/step_definitions/calculator_steps.rb'
    - 'examples/i18n/uz/features/step_definitions/calculator_steps.rb'
